include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 10
    maintainability-index: 50
    maximum-nesting-level: 5
    source-lines-of-code: 50
  rules:
    - always-remove-listener
    - avoid-collection-methods-with-unrelated-types
    - avoid-duplicate-exports
    - avoid-missing-enum-constant-in-map
    - avoid-nested-conditional-expressions
    - avoid-returning-widgets
    - avoid-shrink-wrap-in-lists
    - avoid-throw-in-catch-block
    - avoid-unnecessary-setstate
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - avoid-wrapping-in-padding
    - binary-expression-operand-order
    - check-for-equals-in-render-object-setters
    - consistent-update-render-object
    - double-literal-format
    - format-comment
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    - no-object-declaration
    - prefer-async-await
    - prefer-commenting-analyzer-ignores
    - prefer-conditional-expressions
    - prefer-correct-edge-insets-constructor
    - prefer-correct-type-name
    - prefer-enums-by-name
    - prefer-first
    - prefer-immediate-return
    - prefer-last
    - prefer-match-file-name:
      exclude:
        - lib/main.dart
    - prefer-moving-to-variable
    - prefer-single-widget-per-file
    - prefer-trailing-comma
