name: perlin
description: An implementation of Perlin noise in dart. 
version: 1.0.0
repository: https://github.com/flexagoon/perlin

environment:
  sdk: ">=2.19.1 <3.0.0"

dev_dependencies:
  dart_code_metrics: ^5.6.0
  image: ^4.0.15
  test: ^1.21.0
  very_good_analysis: ^4.0.0+1
